### ISSUE TITLE
Looking to collaborate!

### ISSUE THREAD

**Issue by knownasilya** [BibleJS/bible-reference-parser#1]
I have https://github.com/knownasilya/sword which looks similar to reference-parser. I would love to collaborate to get something that works great!

**Comment by IonicaBizau** [comment]
@knownasilya :star: ed it! :-)

Right now, I am splitting the main module `bible.js` into modules and submodules.

Collaboration is welcome as well! I will add you as member of the organization when these tasks are finished. The work is in progress and I haven't tested anything yet.

**Comment by IonicaBizau** [comment]
@knownasilya I sent you an email. `bible.js` module is stable now, I'm working on terminal application that will be finalized soon.
